// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PracticesModalController from "./practices_modal_controller"
application.register("practices-modal", PracticesModalController)

import TargetsModalController from "./targets_modal_controller"
application.register("targets-modal", TargetsModalController)

import AchievementMessageModalController from "./achievement_message_modal_controller"
application.register("achievement-message-modal", AchievementMessageModalController)
