require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Style/AsciiComments:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*
